server:
  port: 8700
  error:
    include-exception: true

## actuator 管理
#management:
#  endpoints:
#    enabled-by-default: true
#    web:
#      exposure:
#        include: "*"

## 数据源配置
spring:
  application:
    name: service-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.135.13:3306/amzerp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: amzerp
    password: amzerp123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

##eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

  instance:
    instance-id: service-system
    prefer-ip-address: true

## Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      logic-delete-field: status  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: D # 逻辑已删除值(默认为 1)
      logic-not-delete-value: A # 逻辑未删除值(默认为 0)
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 0
      # 默认数据库表下划线命名
      table-underline: true

info:
  app.name: service-system
  company.name: org.jcloud
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


